assets:
  secring.gpg: yegor256/home#assets/secring.gpg
  settings.xml: yegor256/home#assets/jcabi/settings.xml
  pubring.gpg: yegor256/home#assets/pubring.gpg
merge:
  script: |-
    pdd --source=$(pwd) --verbose --file=/dev/null
    mvn clean install -Pqulice --errors --settings ../settings.xml --batch-mode
deploy:
  script: |-
    mvn clean deploy -Pqulice --errors --settings ../settings.xml --batch-mode
release:
  script: |-
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Pqulice -Psonatype -Pjcabi --errors --settings ../settings.xml --batch-mode
    # mvn clean site-deploy -Psite --errors --settings ../settings.xml --batch-mode