# SPDX-FileCopyrightText: Copyright (c) 2012-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: pdd
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  pdd:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: g4s8/pdd-action@master
